# Generated by Django 3.0.3 on 2020-02-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='Student Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=1000, verbose_name='Phone Number')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='RegistrationDate Time')),
            ],
        ),
    ]
